### ISSUE TITLE
`afterModel` alternative for all tasks returned from route

### ISSUE THREAD

**Issue by knownasilya** [knownasilya/ember-data-tasks#6]
A method that takes a hash and returns a modified hash with a new task on it that resolves once all the other tasks resolve on the hash.

```js
return notifyAfterLoad(hash, (hash) => {
  // all tasks have loaded
});
```

cc @allthesignals

**Comment by allthesignals** [comment]
This has been my approach so far, which relies on a newish EC feature, [waitForProperty](http://ember-concurrency.com/api/global.html#waitForProperty)

```javascript
  model(params) {
    const id = bblDemux(params);
    return {
      taskInstance: this.store.findRecord('lot', id),
    };
  },

  setupController(controller, { taskInstance }) {
    this._super(controller, taskInstance);
    this.get('waitToFitBounds').perform(taskInstance);
    // other stuff...
  },

  waitToFitBounds: task(function* (taskInstance) {
    yield waitForProperty(taskInstance, 'state', 'finished');

    // do "afterModel" stuff
    next(() => {
      this.set('mainMap.shouldFitBounds', true);
    });
  }).restartable(),
```

Early adopters of task-based routes might be thrown off by the now-absent conveniences of classic promise-sensitive route hooks like afterModel (and even didTransition, which I think waits for the model), but I don't know what the right approach should be. Should routes be extended to include this as a new hook? Maybe to be conservative it should be called `afterModelTasks` or something. 

Happy to look around this weekend!

Edit: I see, it could just be a route mixin or something.

**Comment by allthesignals** [comment]
Here's where I landed with this, not sure how you would approach it: https://github.com/knownasilya/ember-data-tasks/compare/master...allthesignals:6-after-model-alternative?expand=1. Is `notifyAfterLoad` a utility that is returned from the consumer's model?

**Comment by knownasilya** [comment]
I like the solution, but yes I'd make it more explicit since mixins don't show what's happening, especially if you have multiple, which you are more likely to have on a route. The code example above was just an example, so it doesn't have to be that exact API.

**Comment by allthesignals** [comment]
Alright, I made a much simpler utility: https://github.com/knownasilya/ember-data-tasks/compare/master...allthesignals:6-after-model-utility?expand=1

I have this tested in one of our apps, seems to work well: 
```javascript
    return notifyAfterLoad({
      taskInstance: this.store.findRecord('lot', id),
    }, () => {
      this.set('mainMap.shouldFitBounds', true);
    });
```

I'm not sure how to test this, though. Because it's awaiting the task, it's behaving like a normal route now, but the notification does happen. Will continue to think about this!

EDIT: Not actually sure if that's true ^ - my implementation seems to return the task just fine (in my template I can see `state` change from running to finished). It works but IDK why! I don't think I understand async functions enough.

**Comment by allthesignals** [comment]
@knownasilya Any thoughts? Happy to keep improving on this. Thanks!

**Comment by knownasilya** [comment]
I like that, feel free to submit a PR.

**Comment by knownasilya** [comment]
Probably something like

```js
export default function notifyAfterLoad(hash, callback) {
  waitForProperty(
     Object.values(hash),
    'state',
    'finished',
  ).then(() => callback(hash))l

  return hash;
};
```

**Comment by allthesignals** [comment]
Alright, thanks - I'm not sure it's that simple because waitForProperty isn't thenable. Actually, it was working for me because [`await`](https://babeljs.io/docs/plugins/transform-async-to-generator/) just generates a generator function, which makes sense because [`waitForProperty`](https://github.com/machty/ember-concurrency/pull/205/files#diff-18060a7f1a68902e03bd014496534085R67) is "yieldable". I think this should be a generator function. I'll work on fixing that.

**Comment by knownasilya** [comment]
If you make the whole function async/await (or generator) then the`model` hook will wait till it resolves so your template state will never be able to have the task loading states.

**Comment by allthesignals** [comment]
PR submitted, here's a twiddle with a different approach : https://ember-twiddle.com/fff06c36c9f27525149e126d86e52822?openFiles=routes.application.js%2C
